version: '3.8'

services:
  api_gateway:
    build:
      context: ./APIGateWay
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - orderservice
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./APIGateWay/ocelot.json:/app/ocelot.json

  orderservice:
    build:
      context: ./OrderServiceApp
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=harddb
      - DB_USERNAME=gorbiga
      - DB_PASSWORD=12345679
    command: >
      sh -c "dotnet ef database update && dotnet OrderServiceApp.dll"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: harddb
      POSTGRES_USER: gorbiga
      POSTGRES_PASSWORD: 12345679
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: